### ISSUE TITLE
Howto switch from solder to solder plus

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [stazio/SolderPlus#14]
Howto switch from solder to solder plus without losing all the data (mods/modpacks versions) and the existing connection to the api?

**Comment by gcallant** [comment]
I was just wondering this myself. Considering that prior versions of Solder were migrated using artisan, I also wondered if it would be possible to do an artisan "migration" over to Solder Plus from Solder (assuming it does not crash and burn horribly). I would be interested to find out what the developers' opinion on this is. @stazio

**Comment by stazio** [comment]
After some quick tests, I wrote a wiki page [here](https://github.com/stazio/SolderPlus/wiki/Upgrading-to-SolderPlus-from-the-Original-TechnicSolder) on the "official" way to update.

I know the documentation is...somewhat lacking, I am planning to work on that.

**Comment by gcallant** [comment]
@stazio Thank you for the tests and update. I was just thinking about trying to do a test myself over the weekend and was hoping it would be that simple, but not expecting that at all.
