### ISSUE TITLE
Make the default number of items in pageination configurable. 

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [stazio/SolderPlus#16]
It would be nice if the user could set his preferred number of items on the pageination in modlist, modpack and do on.

**Comment by stazio** [comment]
In almost, if not all, of the tables in SolderPlus, there should be an option to choose the number of "records per page", which is what I believe you are describing.

**Comment by 5t0rmr1d3r** [comment]
You are right, but the default is 10 per page and in my opinion the default or start amount should be customizable per user.
