### ISSUE TITLE
[1.3] In file explorer both backlinks are wrong

### ISSUE THREAD

**Issue by 5t0rmr1d3r** [stazio/SolderPlus#18]
"Return to build" and "Return to modpack" 
Links in file explorer doesn't work

**Comment by stazio** [comment]
Could you provide a more detailed description of this issue? What happens when you press the buttons (what URL do they take you too)? The more details the better.
Looking at it myself I do not see any issues with those buttons so I cannot help.

**Comment by 5t0rmr1d3r** [comment]
I'll deliver tomorrow more information.

**Comment by 5t0rmr1d3r** [comment]
the "return to build" button has the link [http://localhost/modpack/build/8](http://localhost/modpack/build/8)
the "return to modpack" button has the link [http://localhost/modpack/view/1](http://localhost/modpack/view/1)

**Comment by stazio** [comment]
That is how the program should be functioning. The build number and the modpack id are different between builds. In your case the build is #8 and the modpack id is #1.

**Comment by 5t0rmr1d3r** [comment]
No its not!
i get a 404 error.
So it seems that the script doesn't translate "localhost" in the real webadress. 
All other links are working so there has to be a error in some way.

**Comment by stazio** [comment]
Aight you're right. I pushed a fix to the dev branch and will be later pushed to master. If you want to fix it now you can overwrite [this](https://github.com/stazio/SolderPlus/blob/dev/app/views/modpack/build/file-explore.blade.php) file.
I apologize about my confusion.

**Comment by 5t0rmr1d3r** [comment]
Don't worry, just want to help to improve your great work.
